[project]
name = "datafun-06-eda"
version = "0.1.0"
description = "Custom Exploratory Data Analysis Project"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
  "jupyterlab",
  "ipykernel",
  "pandas",
  "numpy",
  "matplotlib",
  "seaborn"
]